### ISSUE TITLE
Implement app with Quarkus

### ISSUE THREAD

**Issue by LordRekishi** [Patlenlix/image-storage#10]
Optional future implementation of this app in Quarkus.
Would require us to make a second repo for this app, and some work to change annotations and such. 
Another option would be to make another release branch and tag the releases with the different frameworks, like Marcus has done for his URL shortener.

**Comment by helenahalldiniths** [comment]
We will remove this for now :) Feel free to do it later on

**Comment by LordRekishi** [comment]
This is a question, and reminder. I'll reopen this again.

**Comment by helenahalldiniths** [comment]
Same here. Me and Felix agreed that it is better not to have any issues present that are not something that we actualy need to do. It is only distracting us from what is imprtant to focus on :)
