### ISSUE TITLE
Change return value from Long to URL

### ISSUE THREAD

**Issue by LordRekishi** [Patlenlix/image-storage#12]
We need to return an URL to the image instead of a Long ID

**Comment by helenahalldiniths** [comment]
We should return a Http respons that has a header with the value of the URL, not the URL it self? Right?

**Comment by LordRekishi** [comment]
> We should return a Http respons that has a header with the value of the URL, not the URL it self? Right?

Yes exactly, we should add a header to the HttpServletResponse: "Location" -> "URL"
