### ISSUE TITLE
Message Queue for resize image process

### ISSUE THREAD

**Issue by LordRekishi** [Patlenlix/image-storage#27]
Implement RabbitMQ to handle resize of pictures asynchronously

**Comment by helenahalldiniths** [comment]
We talked with Martin and he said we don't have to do this. However if you want to try if, feel free!

**Comment by helenahalldiniths** [comment]
Me and Felix agreed that it is better not to have any issues present that are not something that we actualy need to do. It is only distracting us from what is imprtant to focus on :)

**Comment by helenahalldiniths** [comment]
You can alway find it among closed issues if you want to :)
